---
title: "OSCAR benchmarking for various p and optimizer settings"
output: rmarkdown::html_vignette
date: "`r Sys.Date()`"
vignette: >
  %\VignetteIndexEntry{OSCAR benchmarking for various p and optimizer settings}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
\newcommand{\vertiii}[1]{{\left\vert\kern-0.25ex\left\vert\kern-0.25ex\left\vert #1 
    \right\vert\kern-0.25ex\right\vert\kern-0.25ex\right\vert}}
\newcommand{\bbeta}{\boldsymbol{\beta}}      # vector \beta bolded
\newcommand{\bg}{{\boldsymbol{g}}}           # vector g bolded
\newcommand{\bW}{{\boldsymbol{W}}}           # vector W bolded
\newcommand{\x}{{\boldsymbol{x}}}            # vector x bolded

```{r, echo=FALSE}
# For OSCAR methodology; 
library(oscar)
# For 'omics data from prostate cancer;
library(curatedPCaData)
# Surv
library(survival)
```

# OSCAR benchmarking

```{r}

Y1 <- Surv(event=colData(mae_tcga)[["disease_specific_recurrence_status"]], time=colData(mae_tcga)[["days_to_disease_specific_recurrence"]])
X1_samps <- colData(mae_tcga)$sample_name[-which(is.na(Y1))]
Y1 <- Y1[-which(is.na(Y1))]
Y1 <- Y1[-which(!X1_samps %in% colnames(mae_tcga[["gex.rsem.log"]]))]
X1_samps <- X1_samps[-which(!X1_samps %in% colnames(mae_tcga[["gex.rsem.log"]]))]

length(X1_samps)
length(Y1)

X1 <- mae_tcga[["gex.rsem.log"]][,X1_samps]

#> table(apply(X1, MARGIN=1, FUN=function(x) { !all(x==unique(x)[1]) }))
#
#FALSE  TRUE 
#  287 19371
#
# Remove genes with redundant expression, e.g. 0 across all samples
X1 <- X1[which(apply(X1, MARGIN=1, FUN=function(x) { !all(x==unique(x)[1]) })),]

set.seed(1)

t01 <- Sys.time()
oscar_X1_k10_setup1 <- oscar(x=t(X1), y=Y1, family="cox", kmax=10, in_selection=3, percentage=0.01, solver="DBDC")

t01 <- Sys.time()
oscar_X1_k10_setup1 <- oscar(x=t(X1), y=Y1, family="cox", kmax=10, in_selection=3, percentage=0.01, solver="LMBM")
t02 <- Sys.time()
oscar_X1_k20_setup1 <- oscar(x=t(X1), y=Y1, family="cox", kmax=20, in_selection=3, percentage=0.01, solver="LMBM")
t03 <- Sys.time()
oscar_X1_k30_setup1 <- oscar(x=t(X1), y=Y1, family="cox", kmax=30, in_selection=3, percentage=0.01, solver="LMBM")
t04 <- Sys.time()
oscar_X1_k40_setup1 <- oscar(x=t(X1), y=Y1, family="cox", kmax=40, in_selection=3, percentage=0.01, solver="LMBM")
t05 <- Sys.time()
oscar_X1_k50_setup1 <- oscar(x=t(X1), y=Y1, family="cox", kmax=50, in_selection=3, percentage=0.01, solver="LMBM")
t06 <- Sys.time()

oscar_X1_k30_setup1 <- oscar(x=t(X1), y=Y1, family="cox", kmax=30, in_selection=3, percentage=0.005, solver="LMBM")
t07 <- Sys.time()
oscar_X1_k30_setup2 <- oscar(x=t(X1), y=Y1, family="cox", kmax=30, in_selection=3, percentage=0.02, solver="LMBM")
t08 <- Sys.time()
oscar_X1_k30_setup3 <- oscar(x=t(X1), y=Y1, family="cox", kmax=30, in_selection=3, percentage=0.05, solver="LMBM")
t09 <- Sys.time()
oscar_X1_k30_setup4 <- oscar(x=t(X1), y=Y1, family="cox", kmax=30, in_selection=3, percentage=0.10, solver="LMBM")
t10 <- Sys.time()



X2 <- mae_taylor[["gex.rma"]]





```


# Session info

```{r session}
sessionInfo()
```

